### ISSUE TITLE
File transfer to google drive fails after merging dev to master

### ISSUE THREAD

**Issue by KiranPrabhakar135** [didclab/onedatashare#44]
Transfer to Google drive from any source fails with the below exception in log. But, the status of job in queue shows complete.

Stack trace:
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.onedatashare.server.module.googledrive.GoogleDriveResource$GoogleDriveDrain.finish(GoogleDriveResource.java:461)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:236)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:166)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:166)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.complete(FluxGenerate.java:193)
	at org.onedatashare.server.module.vfs.VfsResource$VfsTap.lambda$tap$1(VfsResource.java:154)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:204)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124)
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6877)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532)

**Comment by atulsam** [comment]
It is working in my GoogleDrive branch and It was working in dev also. I am not sure about the master merge.

**Comment by LinusCastelino** [comment]
Pull master and tested. Transfers working when file is transferred into a folder on google drive but not in the parent directory.

**Comment by LinusCastelino** [comment]
Created PR 61 with fix for this issue.

**Comment by atulsam** [comment]
It is working now in master branch. Problem was with root folder because it has id as null.
